### ISSUE TITLE
Unexpected token at @connect

### ISSUE THREAD

**Issue by ac-opensource** [ModusCreateOrg/react-navigation-redux-sample#1]

**Comment by manzznam** [comment]
I get the same error and think its because support for decorators is missing. https://babeljs.io/docs/plugins/transform-decorators/ 

First you need to install the npm module:
`npm install --save-dev babel-plugin-transform-decorators-legacy`

Then ensure that your .babelrc file has this content:
```
{
  "presets": ["react-native"],
  "plugins" :["transform-decorators-legacy"]
}
```

That solved the problem for me

**Comment by j13n** [comment]
I came across the same issue but I solved it by creating a mapStateToProps function and by connecting it with the Redux state:

```javascript
const mapStateToProps = (state) => {
  const { nav } = state

  return { nav }
}

export default connect(mapStateToProps)(AppWithNavigationState)
```

**Comment by jamboapp** [comment]
@januszdotnl can you clarify what you did to make it work?  I think I tried to do what you said, but was unsuccessful.

**Comment by j13n** [comment]
Ah yes I can see now that this was unclear. So basically I've put the following part in a seperate file:
```javascript
@connect(state => ({
    nav: state.nav
}))
class AppWithNavigationState extends Component {
    render() {
        return (
            <AppNavigator
                navigation={addNavigationHelpers({
                    dispatch: this.props.dispatch,
                    state: this.props.nav
                })}
            />
        );
    }
}
```

So you can remove this part and the other file would look something like this:
```javascript
import React, { Component } from "react";
import { Provider, connect } from "react-redux";
import AppNavigator from './Some/Location'

class AppWithNavigationState extends Component {
    render() {
        return (
            <AppNavigator
                navigation={addNavigationHelpers({
                    dispatch: this.props.dispatch,
                    state: this.props.nav
                })}
            />
        );
    }
}

const mapStateToProps = (state) => {
  const { nav } = state

  return { nav }
}

export default connect(mapStateToProps)(AppWithNavigationState)
```
Just watch out with the imports and everything I haven't tested this but it is pretty close of what I have.

**Comment by stan229** [comment]
Yes, you need to have decorators enabled. @manzznam is correct.
