### ISSUE TITLE
Outdated getting errors when running 

### ISSUE THREAD

**Issue by isAlmogK** [ModusCreateOrg/react-navigation-redux-sample#2]
Outdated getting errors when running

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
