### ISSUE TITLE
doesnt compile

### ISSUE THREAD

**Issue by PerspectivesLab** [ModusCreateOrg/react-navigation-redux-sample#3]
1/ download the package
2/ npm install in directory
3/ node node_modules/react-native/local-cli/cli.js run-android

error: undefined is not a function: handleorientationchange

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
