### ISSUE TITLE
Undefined is not an object (evaluating'_reactNative.Deviceinfo.isIPhoneX_deprecated) Error

### ISSUE THREAD

**Issue by RajNarayanan** [ModusCreateOrg/react-navigation-redux-sample#4]
Undefined is not an object (evaluating'_reactNative.Deviceinfo.isIPhoneX_deprecated) Error . How to resolve this. please mail as soon as possible.

**Comment by adeconsulting** [comment]
I encountered the same error when trying to launch this sample app on my MotoX phone that's running Android 5.1

**Comment by LittleYenMin** [comment]
Update your React and React-Native version

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
